### ISSUE TITLE
If I want to implement milvus_to_milvus offline transfer, how should I configure it?

### ISSUE THREAD

**Issue by 0sengseng0** [zilliztech/vts#20]
I want to transfer a specific database from one milvus server offline to another server. What should I do?

**Comment by 0sengseng0** [comment]
If I need to transfer offline between two servers that are not connected to the network, is this solution not feasible?

**Comment by nianliuu** [comment]
how do you connect your milvus server in local, vts use the same ip. If your server is offline and the collection is not load. Yes, it doesn't work, as VTS is using query iterator to read data from your milvus and upsert it into another one.

For offline solution, you can go check milvus backup and migration: https://github.com/milvus-io/milvus-tools, https://github.com/zilliztech/milvus-backup
