### ISSUE TITLE
Can it support configuring multiple collections on the source side in a task?

### ISSUE THREAD

**Issue by herbert2008** [zilliztech/vts#23]
Can it support configuring multiple collections on the source side in a task?

**Comment by nianliuu** [comment]
yeah, sure. You can migrate a whole db if the collection param is not set. For multiple collection, currently you can only define multiple source config instead. As the transformer connector not support multiple collection. We will make collection param a list in the future to better support this.

For example:

curl --location --request POST 'http://127.0.0.1:5801/hazelcast/rest/maps/submit-job' \
--header 'Content-Type: application/json' \
--data-raw '
{
  "env": {
    "execution.parallelism": 2,
    "job.mode": "BATCH"
  },
  "source": [
    {
      "plugin_name": "Milvus",
      "url": "https://in01-***.aws-us-west-2.vectordb.zillizcloud.com:19530",
      "token": "***",
      "database": "default",
      "collection": "book",
      "result_table_name": "book"
    },
    {
      "plugin_name": "Milvus",
      "url": "https://in01-***.aws-us-west-2.vectordb.zillizcloud.com:19530",
      "token": "***",
      "database": "default",
      "collection": "book2",
      "result_table_name": "book2"
    }
  ],
  "sink": [
    {
      "plugin_name": "Milvus",
      "source_table_name": "book",
      "url": "https://in01-***.aws-us-west-2.vectordb.zillizcloud.com:19542",
      "token": "***",
      "database": "default",
      "batch_size": 10
    },
    {
      "plugin_name": "Milvus",
      "source_table_name": "book2",
      "url": "https://in01-***.aws-us-west-2.vectordb.zillizcloud.com:19542",
      "token": "***",
      "database": "default",
      "batch_size": 10
    }
  ]
}
'

**Comment by herbert2008** [comment]
got it，thanks~

**Comment by nianliuu** [comment]
@herbert2008 We add a new params collections which is a list. No need to add several configs now
